version: '3.2'

services:
  php-apache:
    image: php:8.1.16-apache
    build:
      context: .
      dockerfile: dockerfile-php-apache
    container_name: sanjadutra_php_apache
    volumes:
      - ./_web:/var/www/html
    ports:
      - 88:80
    networks:
      rede:
        ipv4_address: 170.17.0.2
    working_dir: /var/www/html
    environment:
      PHP_ERROR_REPORTING: E_ALL & ~E_NOTICE
      PHP_DISPLAY_ERRORS: "Off"
      PHP_DISPLAY_STARTUP_ERRORS: "Off"
      PHP_LOG_ERRORS: "On"
      PHP_MAX_EXECUTION_TIME: 60
      PHP_MEMORY_LIMIT: 128M
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M
      TZ: "America/Sao_Paulo"
    depends_on:
          - db

  db:
    image: mariadb:latest
    build:
      context: .
      dockerfile: dockerfile-db
    container_name: sanjadutra_db
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      rede:
        ipv4_address: 170.17.0.3
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_ccr
      MYSQL_USER: aluno
      MYSQL_PASSWORD: my-password
      TZ: "America/Sao_Paulo"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sanjadutra_phpmyadmin
    ports:
      - 8087:80
    networks:
      rede:
        ipv4_address: 170.17.0.4
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my-secret-pw
      UPLOAD_LIMIT: 50M
      #PMA_USER: aluno
      #PMA_PASSWORD: my-password
      TZ: "America/Sao_Paulo"
    depends_on:
      - db

  python-ccr:
    build:
      context: .
      dockerfile: dockerfile-python-ccr
    container_name: sanjadutra_python_ccr
    restart: always
    volumes:
      - ./_app:/app 
    tty: true
    networks:
      rede:
        ipv4_address: 170.17.0.5
    environment:
      TZ: "America/Sao_Paulo"

volumes:
  dbdata:

networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 170.17.0.0/24
          gateway: 170.17.0.1